In [1]:
import numpy as np

In [29]:
#display array
arr1=np.array([1,2,3,4])
arr1
print(arr1[-1])   # find last element in array
print(arr1[2])

4
3


In [3]:
# find datatype
arr1.dtype

dtype('int32')

In [4]:
# find shape
arr1.shape

(4,)

In [5]:
arr1.ndim

1

In [6]:
arr1.size

4

In [10]:
# 1D array
x=np.array([2,4,6])
x

array([2, 4, 6])

In [15]:
# 2D array
y=np.array([[10,20,30],[20,30,40]])
y

array([[10, 20, 30],
       [20, 30, 40]])

In [16]:
# 3D array
z=np.array([[50,60,70],[80,90,10],[20,30,40]])
z

array([[50, 60, 70],
       [80, 90, 10],
       [20, 30, 40]])

In [41]:
# arrange function in arrray
a=np.arange(1,5)
print(a)
index_max=np.argmax(a)   # max index in array
print(index_max)


3


In [32]:
# reshape fun
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b
b.reshape(1,9)


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [39]:
# mathematical operation on array
p=np.array([[1,2,3],[4,5,6],[3,5,7]])
print(p)
q=np.array([[10,20,30],[40,50,60],[3,2,1]])
print(q)
print('----------------')
s=p+q
print(s)
print('----------------')
r=p*q
print(r)
print('-----------------')
print(p/q)

[[1 2 3]
 [4 5 6]
 [3 5 7]]
[[10 20 30]
 [40 50 60]
 [ 3  2  1]]
----------------
[[11 22 33]
 [44 55 66]
 [ 6  7  8]]
----------------
[[ 10  40  90]
 [160 250 360]
 [  9  10   7]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [1.  2.5 7. ]]
