In [12]:
import numpy as np


In [2]:
zeros_arr = np.zeros(5,dtype='int')
zeros_arr


array([0, 0, 0, 0, 0])

In [10]:
arr1=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
print(arr1)
print(arr1.dtype)
arr1.shape
swapp=np.swapaxes(arr1,0,1)
print(swapp)
max=arr1.max()
max
arr1 = np.linspace(0, 10, 5)
print(arr1)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
int32
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[ 0.   2.5  5.   7.5 10. ]


In [11]:
a=12.5
print(type(a))


<class 'float'>
